files:
  - source: /source/tr/Ukrainian2.xml
    translation: /translation/%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        it: Italian
    translate_content: '0'
    translate_attributes: '0'
    content_segmentation: '0'
