files:
  - source: /source
    ignore:
      - /source/test_file.txt
      - /source/coma.csv
    translation: translation/%two_letters_code7%/<
    languages_mapping:
      two_letters_code:
        it: Italian
    first_line_contains_header: '1'
    scheme: 
    translate_content: '0'
    translate_attributes: '0'
    content_segmentation: '0'
