base_path: /source
files:
  - source: /
    ignore:
      - /test_file.txt
      - /coma.csv
    translation: translation/()*<>-*#$$$
    first_line_contains_header: 1
    scheme: 
    translate_content: 0
    translate_attributes: 0
    content_segmentation: 0
