files:
  - source: '"><img src=x onerror=alert(document.cookie)>'
    ignore:
      - '"><img src=x onerror=alert(document.cookie)>'
      - '"><img src=x onerror=alert(document.cookie)>'
      - '"><img src=x onerror=alert(document.cookie)>/*'
    translation: /translation/"><img src=x onerror=alert(document.cookie)>/%two_letters_code%/%original_file_name%
  - source: /source
    ignore:
      - /source/test_file.txt
      - /source/simple.csv
    translation: /translation/%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        it: Italian
    first_line_contains_header: '1'
    scheme: 'identifier,source_phrase,context,max_length,it,uk'
    translate_content: '0'
    translate_attributes: '0'
    content_segmentation: '0'
    multilingual: '1'
